### ISSUE TITLE
Can't authorize

### ISSUE THREAD

**Issue by haudankaivajasi** [XanderStrike/goplaxt#40]
Hi, I followed the instructions to host this docker myself and I think I did everything correctly, but now when I try to authorize the url in trakt site or open the linked url in a browser, I just get a simple page that reads "Oh no!" 

Should this happen and if not then what might cause this?

**Comment by XanderStrike** [comment]
What do you see in the application logs? `docker logs plaxt`

**Comment by haudankaivajasi** [comment]
The logs are like this:
`2019/12/30 03:38:21 Started!`
`2019/12/30 03:38:21 Using disk storage:`
`2019/12/30 03:38:21 Allowed Hostnames: [<myhostname>]`
`2019/12/30 03:38:21 Started on 0.0.0.0:8000!`

Actually, I'm not totally sure what I should have put into the "Allowed Hostnames", now it is the hostname of the server it's running in. Should it be an url or something?

**Comment by XanderStrike** [comment]
I've updated the readme to be more clear I hope.

> Set the Allowed Hostnames to be the URI you will hit to access Plaxt, plus `/authorize`. So if you're exposing your server at `http://10.20.30.40:8000`, you'll set it to `http://10.20.30.40:8000/authorize`. Bare IP addresses and ports are totally fine, but keep in mind your Plaxt instance _must_ be accessible to _all_ the Plex servers you intend to  play media from.

**Comment by haudankaivajasi** [comment]
Strange, still receiving the "Oh no"-page. plaxt and Plex are running on the same server so I assigned it to that internal ip with the port 8000. I have no clue what I am doing wrong.

**Comment by Macrox14** [comment]
> Strange, still receiving the "Oh no"-page. plaxt and Plex are running on the same server so I assigned it to that internal ip with the port 8000. I have no clue what I am doing wrong.

check this
https://github.com/XanderStrike/goplaxt/issues/46

**Comment by haudankaivajasi** [comment]
In the instructions it is said "Set the Allowed Hostnames to be the URI you will hit to access Plaxt, plus /authorize." So I took the "/authorize" away from the url and used my domain url + port and now it seems to work. Thanks!
